In [2]:
 #1 . Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np
arr = np.arange(6)
print("Array",arr)
print("Data type",arr.dtype)


Array [0 1 2 3 4 5]
Data type int64


In [6]:
#2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5,2.6,3.7])
print(arr.dtype)


float64


In [7]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j,2+3j,4+5j])
print(arr.dtype)

complex128


In [4]:
#4.Convert an existing NumPy array 'arr' of integers to float32 data type
arr = np.array([0,1,2,3,4,5])
arr_float32 = arr.astype(np.float32)

print("converted array",arr_float32)
print("Data type:", arr_float32.dtype)

converted array [0. 1. 2. 3. 4. 5.]
Data type: float32


In [7]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision
import numpy as np
arr = np.array([0.123456789, 1.23456789, 2.3456789])
arr_float32 = arr.astype(np.float32)

print(arr_float32.dtype)
print("data type of given arr",arr.dtype)

float32
data type of given arr float64


In [17]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.
import numpy as np

def arr_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape,size,dtype

arr = np.array([1,2,3,4,5,6])
arr2 = arr_attributes(arr)
print(arr2)



((6,), 6, dtype('int64'), 1)


In [19]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
import numpy as np

def array_dimensions(arr):
    dimensions = arr.ndim
    return dimensions
    
arr = np.array([[2,3,4,5,6,7,8]])
arr2 = array_dimensions(arr)
print(arr2)

2


In [22]:
#8 Design a function item_size_info that takes a NumPy array as input and returns the item size and the totalsize in bytes.
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size,total_size

arr = np.array([4,5,6,7,8,9])
item_size,total_size = item_size_info(arr)
print("item_size",item_size)
print("total_size",total_size)

item_size 8
total_size 48


In [24]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    strides = arr.strides
    return strides

arr = np.array([[1,2,3],[4,5,6]])
strides = array_strides(arr)
print(strides)

(24, 8)


In [26]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shapeand strides of the array.

def shape_stride_relationship(arr):
    strides = arr.strides
    shape = arr.shape
    return strides,shape

arr = np.array([[3,4,5,6],[7,8,9,10]])
strides,shape = shape_stride_relationship(arr)
print(strides)
print(shape)

(32, 8)
(2, 4)


In [30]:
#11 Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array ofzeros with `n` elements
def create_zeros_array(n):
    return np.zeros(n,dtype = int)

n = 5
zero_arr = create_zeros_array(n)
print(zero_arr)

[0 0 0 0 0]


In [3]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2DNumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(rows,cols):
    one_matrix = np.ones((rows,cols))
    return one_matrix

rows,cols = 3,4
matrix = create_ones_matrix(3,4)
print(matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
#step`.

def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

start,stop,step = 0,10,2
arr = generate_range_array(start,stop,step)
print(arr)

[0 2 4 6 8]


In [10]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop`(inclusive).

def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)

start,stop,num = 1,5,10
arr = generate_linear_space(start,stop,num)
print(arr)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [12]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
#identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    arr = np.eye(n)
    return arr

n = 4
arr2 =  create_identity_matrix(n)
print(arr2)
    
    

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
#16. Write a function that takes a Python list and converts it into a NumPy array

def list_python(l):
    return np.array(l)

l = [1,2,3,4,5]
arr = list_python(l)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [19]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data
import numpy as np

# Create an initial NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Use numpy.view to create a new array object with the same data
view_array = original_array.view()

# Print both arrays and their memory addresses
print("Original array:", original_array)
print("View array:", view_array)

print("\nMemory addresses:")
print("Original array data address:", original_array.__array_interface__['data'])
print("View array data address:", view_array.__array_interface__['data'])

# Modify the view array and show that the original array is also affected
view_array[0] = 10
print("\nAfter modifying the view array:")
print("Original array:", original_array)
print("View array:", view_array)


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]

Memory addresses:
Original array data address: (93906214258336, False)
View array data address: (93906214258336, False)

After modifying the view array:
Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]


In [21]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenates(arr1,arr2,axis = 0):
    return np.concatenate((arr1,arr2),axis = axis)

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8])
concat = concatenates(arr1,arr2)
print("concat array is ",concat)
    
    

concat array is  [1 2 3 4 5 6 7 8]


In [26]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5],[6]])

concat = np.concatenate((arr1,arr2),axis = 1)
print(concat)

[[1 2 5]
 [3 4 6]]


In [27]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.
import numpy as np

def stack_arrays_vertically(arrays):
    """
    Vertically stacks multiple NumPy arrays from a list.

    Parameters:
    arrays (list of numpy.ndarray): List of arrays to be stacked.

    Returns:
    numpy.ndarray: The stacked array.
    """
    try:
        stacked_array = np.vstack(arrays)
        return stacked_array
    except ValueError as e:
        return str(e)

# Example usage
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

result = stack_arrays_vertically([arr1, arr2, arr3])
print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
#with a given step size.



def range_array(start,stop,step):
    return np.arange(start,stop,step)

start = 0
stop = 10
step = 2

result = range_array(start,stop,step)
print(result)

[0 2 4 6 8]


In [29]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1(inclusive).
def equally_spaced(start,stop,num):
    return np.linspace(start,stop,num)

start = 0
stop = 1
num = 10

matrix = equally_spaced(start,stop,num)
print(matrix)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [30]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and1000 (inclusive).

def generate_logarithmically_spaced_values(start, stop, num_values):
    return np.logspace(start, stop, num_values)

start = 0  # log base 10 of 1
stop = 3  # log base 10 of 1000
num_values = 5

result = generate_logarithmically_spaced_values(start, stop, num_values)
print(result)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [31]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
#are random integers between 1 and 100

In [1]:
#25.25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
#with zeros. Use NumPy operations within the Pandas DataFrame.

In [8]:
#26.. Access the 3rd element from the given NumPy array.
arr = np.array([10,20,30,40,50])
print(arr[2])

30


In [7]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[1][2])

6


In [11]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
mask = arr > 5
elmnt_greatr_5 = arr[mask]
print(elmnt_greatr_5)

[ 8 10  7]


In [15]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[1:6])

[2 3 4 5 6]


In [17]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[0:2,1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [18]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
#provided in another array.

import numpy as np

def extract_elements_by_indices(arr_2d, indices):
 
    return arr_2d[indices[:, 0], indices[:, 1]]

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([[0, 2],
                    [1, 1],
                    [2, 0]])

result = extract_elements_by_indices(arr_2d, indices)
print(result)


[3 5 7]


In [19]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
#boolean indexing.
import numpy as np

def filter_elements_greater_than_threshold(arr, threshold):
    return arr[arr > threshold]

# Example usage
arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5

filtered_elements = filter_elements_greater_than_threshold(arr, threshold)
print(filtered_elements)


[ 8 10  7]


In [20]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
#separate arrays for each dimension

import numpy as np

def extract_elements_from_3d_array(arr_3d, x_indices, y_indices, z_indices):
 
    return arr_3d[x_indices, y_indices, z_indices]

# Example usage
arr_3d = np.array([[[ 1,  2,  3],
                    [ 4,  5,  6],
                    [ 7,  8,  9]],
                   
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 0, 2])
z_indices = np.array([2, 1, 0])

extracted_elements = extract_elements_from_3d_array(arr_3d, x_indices, y_indices, z_indices)
print(extracted_elements)


[ 6 11 25]


In [21]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np

def filter_elements_by_two_conditions(arr, condition1, condition2):
    return arr[condition1 & condition2]

# Example usage
arr = np.array([3, 8, 2, 10, 5, 7])

# Define two conditions
condition1 = arr > 5    # Elements greater than 5
condition2 = arr % 2 == 0  # Elements that are even

filtered_elements = filter_elements_by_two_conditions(arr, condition1, condition2)
print(filtered_elements)


[ 8 10]


In [22]:
#35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.\
import numpy as np

def extract_elements_by_indices(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]


arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])

extracted_elements = extract_elements_by_indices(arr_2d, row_indices, col_indices)
print(extracted_elements)


[3 4 8]


In [27]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr1 = np.random.randint(1,10,(3,3))

arr1 + 5

array([[ 7,  7,  6],
       [12, 11,  7],
       [14, 14,  7]])

In [28]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
#corresponding element in arr1 using NumPy broadcasting.
import numpy as np


arr1 = np.array([[2, 3, 4]])  
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  


result = arr2 * arr1.T

print(result)



[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [33]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.random.randint(1,10,(1,4))
arr2 = np.random.randint(1,10,(4,3))

arr1 + arr2
# we cant add them this shape of matrix

In [37]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.random.randint(1,10,(3,1))
arr2 = np.random.randint(1,10,(1,3))

arr1 + arr2

array([[11,  4,  7],
       [ 9,  2,  5],
       [17, 10, 13]])

In [40]:
#40 Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
#broadcasting. Handle the shape incompatibility 

import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  
arr2 = np.array([[1, 2], [3, 4]])         


arr1_reshaped = arr1[:, np.newaxis, :]



result = arr1_reshaped * arr2


print(result)


In [43]:
#41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np


arr = np.array([[1, 2, 3], [4, 5, 6]])

column_means = np.mean(arr, axis=0)


print("Column-wise means:", column_means)


Column-wise means: [2.5 3.5 4.5]


In [45]:
#42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,axis = 1)

array([3, 6])

In [47]:
#43.For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,axis = 1)

array([3, 6])

In [48]:
#44 For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

def moving_sum(arr, window_size):

    
    result = np.zeros((arr.shape[0], arr.shape[1] - window_size + 1))

    for i in range(arr.shape[0]):
        
        result[i, :] = np.convolve(arr[i, :], np.ones(window_size), mode='valid')

    return result


arr = np.array([[1, 2, 3], [4, 5, 6]])

window_size = 2


moving_sums = moving_sum(arr, window_size)


print("Moving sums along rows:")
print(moving_sums)


Moving sums along rows:
[[ 3.  5.]
 [ 9. 11.]]


In [2]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])


all_even = True


num_columns = arr.shape[1]


for col in range(num_columns):
  
    if not np.all(arr[:, col] % 2 == 0):
        all_even = False
        break


all_even



False

In [3]:
#46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the  reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
after_reshape = original_array.reshape(6,1)
print(after_reshape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [4]:
#47. Create a function that takes a matrix as input and returns the flattened array


def flatten_array(inpur_matrix):
    return input_matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flt = flatten_array(input_matrix)
print(flt)

[1 2 3 4 5 6]


In [9]:
#48. Write a function that concatenates two given arrays along a specified axis.
def concatenate_arr(arr1,arr2,axis):
    return np.concatenate((arr1,arr2),axis = axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concat =  concatenate_arr(arr1,arr2,axis = 0)
print(concat)

concat2 =  concatenate_arr(arr1,arr2,axis = 1)
print(concat2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [12]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.
import numpy as np

def split_array(array, indices_or_sections, axis):
   
    return np.split(array, indices_or_sections, axis=axis)

# Define the original array
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split the array along different axes
split_along_axis0 = split_array(original_array, 2, axis=0)
split_along_axis1 = split_array(original_array, 2, axis=1)
split_at_indices = split_array(original_array, [1, 2], axis=1)

# Output the results
print("Split along axis 0:")
for sub_array in split_along_axis0:
    print(sub_array)

print("\nSplit along axis 1:")
for sub_array in split_along_axis1:
    print(sub_array)

print("\nSplit at specified indices along axis 1:")
for sub_array in split_at_indices:
    print(sub_array)




In [1]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
import numpy as np

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert values at specified indices
    for index, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, index, value)
    
    # Sort indices to delete in reverse order to avoid index shifting issues
    indices_to_delete_sorted = sorted(indices_to_delete, reverse=True)
    
    # Delete elements at specified indices
    for index in indices_to_delete_sorted:
        original_array = np.delete(original_array, index)
    
    return original_array

# Define the original array
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Modify the array
modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

# Output the modified array
print("Modified array:", modified_array)






Modified array: [ 1 10 11  4  5]


In [16]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
 #Perform element-wise addition between `arr1` and `arr2
arr1 = np.random.randint(0,10,size = (10,))
arr2 = np.arange(1,11)
arr1 + arr2

array([ 4, 11,  5,  7, 12,  8, 14, 16, 14, 15])

In [22]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
 #from 1 to 10. Subtract `arr2` from `arr1` element-wise
    
arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)

arr1 - arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [23]:
#53.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
#Perform element-wise multiplication between `arr1` and `arr2`.

import numpy as np


arr1 = np.random.randint(0, 10, size=(5,)) 
arr2 = np.arange(1, 6)

result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise multiplication result:", result)
arr1

arr1: [3 7 6 9 7]
arr2: [1 2 3 4 5]
Element-wise multiplication result: [ 3 14 18 36 35]


array([3, 7, 6, 9, 7])

In [30]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
#to 5. Perform element-wise division of `arr1` by `arr2`.
arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)

arr1 / arr2

array([2., 2., 2., 2., 2.])

In [37]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
#reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1 = np.arange(1,6)
arr2 = np.arange(5,0,-1)
np.power(arr1,arr2)

array([ 1, 16, 27, 16,  5])

In [39]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
import numpy as np

def count_substring_occurrences(arr, substring):
    return np.char.count(arr, substring).sum()


arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
count = count_substring_occurrences(arr, substring)

print(f"The substring '{substring}' occurs {count} times in the array.")


The substring 'hello' occurs 3 times in the array.


In [40]:
#57.Write a function that extracts uppercase characters from a NumPy array of strings

def string_upper(arr):
    return np.char.upper(arr)

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
arr2 = string_upper(arr)
print(arr2)
    

['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [41]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np

def replace_substring(arr, old_substring, new_substring):
   
    return np.char.replace(arr, old_substring, new_substring)


arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'
result = replace_substring(arr, old_substring, new_substring)

print("Original array:", arr)
print("Modified array:", result)


Original array: ['apple' 'banana' 'grape' 'pineapple']
Modified array: ['orange' 'banana' 'grape' 'pineorange']


In [45]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

import numpy as np

def concatenate_strings_elementwise(arr1, arr2):
    return np.char.add(arr1, arr2)


arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_strings_elementwise(arr1, arr2)

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise concatenation result:", result)



arr1: ['Hello' 'World']
arr2: ['Open' 'AI']
Element-wise concatenation result: ['HelloOpen' 'WorldAI']


###### 

In [46]:
#60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


import numpy as np

def length_of_longest_string(arr):
    len_vectorized = np.vectorize(len)
    lengths = len_vectorized(arr)
    return np.max(lengths)

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = length_of_longest_string(arr)

print("Array:", arr)
print("Length of the longest string:", longest_length)


Array: ['apple' 'banana' 'grape' 'pineapple']
Length of the longest string: 9


In [10]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
#standard deviation of the dataset using NumPy's functions

arr = np.random.randint(1,1001,size = 100)
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))

500.74
500.0
73716.01239999999
271.5069288250302


In [14]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
arr = np.random.randint(1,101,size = 50)
print(np.percentile(arr,25))
print(np.percentile(arr,75))

31.25
84.75


In [15]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
#arrays using NumPy's `corrcoef` function.
import numpy as np


array1 = np.random.randint(1, 100, size=100)
array2 = np.random.randint(1, 100, size=100)


correlation_matrix = np.corrcoef(array1, array2)
correlation_coefficient = correlation_matrix[0, 1]


print("Array 1:", array1)
print("Array 2:", array2)
print("Correlation coefficient:", correlation_coefficient)


Array 1: [25 91 71 81 44 30  7 77 60 70 57 70 81 74 55 56 32 40 15 39 28 12 18 23
 78 82 34 28 99 60 18 74  9 33  7 80 96 16 22  2 52 73 17 10 97 94 80 62
 87 94 74 91 27 57 45 16 91 47 53 64  5 17 86 89 34 47 98  9 89 38 67 22
 69 27 31 41 26 80 69 55 41 33  5 15 44 64 96 30 37 16  4 39 88 45 78 16
 88 56 82 37]
Array 2: [32 68 20 27 63 42 92 24 95 84  6  5  6 38 56 88  2 85 14 10 85 50 53 65
  3 71 69 83 44 65 73  7 40 55 99 91 54 42 36  6 68 30 62 60 65 15 40 15
 94 67 86 54 21 34 22 96 44 54 13 65 92 79 92 45  7 84 35 78 30 74 90  5
 71  4 19 63  4 24 33  3 98 29 78 32 91 72 31 12 97 49 35 54 40 70 54 25
 40  3 32 76]
Correlation coefficient: -0.07940729762286927


In [16]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
import numpy as np


matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])


result = np.dot(matrix1, matrix2)


print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(result)


Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [17]:
#65.Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
#percentiles along with the first and third quartiles.

import numpy as np


array = np.random.randint(10, 1001, size=50)


percentile_10 = np.percentile(array, 10)
percentile_50 = np.percentile(array, 50)  # This is also the median
percentile_90 = np.percentile(array, 90)

# Calculate the first and third quartiles
first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

# Print the array and the calculated percentiles
print("Array:", array)
print("10th percentile:", percentile_10)
print("50th percentile (median):", percentile_50)
print("90th percentile:", percentile_90)
print("First quartile (25th percentile):", first_quartile)
print("Third quartile (75th percentile):", third_quartile)


Array: [ 586  864  371  301  424  237  172   89  249 1000  995  498  273  150
  613  991   86   83   94  510  863  278  898  965  341  626  621  278
  684  505  105  332  557  881  595  500  263  146  885  922  197  603
  145  334  809  555  685  427  357   47]
10th percentile: 103.9
50th percentile (median): 462.5
90th percentile: 900.4000000000001
First quartile (25th percentile): 252.5
Third quartile (75th percentile): 669.5


In [18]:
#66. Create a NumPy array of integers and find the index of a specific element.
import numpy as np

# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Define the specific element to find
element_to_find = 50

# Find the index of the specific element
index = np.where(array == element_to_find)[0]

# Print the array and the index of the specific element
print("Array:", array)
print(f"Index of element {element_to_find}:", index)


Array: [ 10  20  30  40  50  60  70  80  90 100]
Index of element 50: [4]


In [19]:
#67.Generate a random NumPy array and sort it in ascending order.
import numpy as np

random_array = np.random.randint(1, 101, size=20)
sorted_array = np.sort(random_array)

print("Original array:", random_array)
print("Sorted array:", sorted_array)


Original array: [23 18 46 52  2 84  5 55 43 84 60 13 88 20 88 28 23 29 52 80]
Sorted array: [ 2  5 13 18 20 23 23 28 29 43 46 52 52 55 60 80 84 84 88 88]


In [20]:
#68.. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

import numpy as np


arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print("Original array:", arr)
print("Filtered array (elements > 20):", filtered_arr)


Original array: [12 25  6 42  8 30]
Filtered array (elements > 20): [25 42 30]


In [21]:
#69.69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
import numpy as np


arr = np.array([1, 5, 8, 12, 15])


filtered_arr = arr[arr % 3 == 0]


print("Original array:", arr)
print("Filtered array (elements divisible by 3):", filtered_arr)


Original array: [ 1  5  8 12 15]
Filtered array (elements divisible by 3): [12 15]


In [22]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
import numpy as np


arr = np.array([10, 20, 30, 40, 50])

filtered_arr = arr[(arr >= 20) & (arr <= 40)]


print("Original array:", arr)
print("Filtered array (elements ≥ 20 and ≤ 40):", filtered_arr)


Original array: [10 20 30 40 50]
Filtered array (elements ≥ 20 and ≤ 40): [20 30 40]


In [24]:
#71.For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
import numpy as np

# Create the NumPy array
arr = np.array([1, 2, 3])

# Check the byte order
byte_order = arr.dtype.byteorder

# Print the byte order
print("Byte order:", byte_order)


Byte order: =


In [25]:
#72.For the given NumPy array, perform byte swapping in place using byteswap().
arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

# Create the NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(inplace=True)

# Print the array after byte swapping
print("Array after byte swapping:", arr)


Array after byte swapping: [16777216 33554432 50331648]


In [26]:
#73.For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
 
arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()


print("Original array:", arr)
print("Array with swapped byte order:", swapped_arr)



Original array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


In [27]:
#74.. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

# Print the original and swapped arrays
print("Original array:", arr)
print("Array with swapped byte order:", swapped_arr)


Original array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


In [3]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
import sys


arr = np.array([1, 2, 3], dtype=np.int32)


array_byteorder = arr.dtype.byteorder


system_byteorder = '<' if sys.byteorder == 'little' else '>'


if array_byteorder in ['|', '=']:
   
    needs_swap = False
else:
    needs_swap = array_byteorder != system_byteorder

# Output the result
print("Array byte order:", array_byteorder)
print("System byte order:", system_byteorder)
print("Byte swapping necessary:", needs_swap)


Array byte order: =
System byte order: <
Byte swapping necessary: False


In [4]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

import numpy as np

arr1 = np.arange(1, 11)

copy_arr = arr1.copy()


copy_arr[0] = 99

print("arr1:", arr1)
print("copy_arr:", copy_arr)
print("Does modifying copy_arr affect arr1?", np.array_equal(arr1, copy_arr))


arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [99  2  3  4  5  6  7  8  9 10]
Does modifying copy_arr affect arr1? False


In [5]:
#77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
#the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

import numpy as np

matrix = np.random.randint(1, 100, size=(3, 3))


view_slice = matrix[0:2, 0:2] 


view_slice[0, 0] = 999
print("Original matrix after modification:")
print(matrix)
print("view_slice:")
print(view_slice)


Original matrix after modification:
[[999  60  93]
 [ 19  10   6]
 [ 22  59  66]]
view_slice:
[[999  60]
 [ 19  10]]


In [8]:
#78.. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
#`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

import numpy as np


array_a = np.arange(1, 13).reshape(4, 3)


view_b = array_a[1:3, :]  


original_array_a_before_modification = array_a.copy()


view_b += 5

original_array_a_after_modification = array_a.copy()

print("Original array_a before modification:")
print(original_array_a_before_modification)
print("Original array_a after modification:")
print(original_array_a_after_modification)
print("view_b after broadcasting addition of 5:")
print(view_b)


Original array_a before modification:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Original array_a after modification:
[[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [10 11 12]]
view_b after broadcasting addition of 5:
[[ 9 10 11]
 [12 13 14]]


In [9]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
#`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
#reflects changes in the original `orig_array`.

import numpy as np

#
orig_array = np.arange(1, 9).reshape(2, 4)


reshaped_view = orig_array.reshape(4, 2)


original_array_before_modification = orig_array.copy()


reshaped_view[0, 0] = 999


original_array_after_modification = orig_array.copy()

print("Original array before modification:")
print(original_array_before_modification)
print("Original array after modification:")
print(original_array_after_modification)
print("Reshaped view after modification:")
print(reshaped_view)


Original array before modification:
[[1 2 3 4]
 [5 6 7 8]]
Original array after modification:
[[999   2   3   4]
 [  5   6   7   8]]
Reshaped view after modification:
[[999   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [11]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
#elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

import numpy as np


data = np.random.randint(1, 10, size=(3, 4))

data_copy = data[data > 5].copy()

original_data_before_modification = data.copy()


if data_copy.size > 0:  
    data_copy[0] = 999


original_data_after_modification = data.copy()

print("Original data before modification:")
print(original_data_before_modification)
print("Original data after modification:")
print(original_data_after_modification)
print("data_copy after modification:")
print(data_copy)


Original data before modification:
[[6 2 7 8]
 [5 6 1 5]
 [2 9 2 5]]
Original data after modification:
[[6 2 7 8]
 [5 6 1 5]
 [2 9 2 5]]
data_copy after modification:
[999   7   8   6   9]


In [13]:
#81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction
#operations between them.
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))
print(arr1)
print(arr2)

add = arr1 + arr2
print("add",add)

sub = arr1 - arr2
print("subb",sub)

[[6 2 6]
 [6 4 5]
 [5 7 2]]
[[7 3 7]
 [4 5 4]
 [4 7 8]]
add [[13  5 13]
 [10  9  9]
 [ 9 14 10]]
subb [[-1 -1 -1]
 [ 2 -1  1]
 [ 1  0 -6]]


In [15]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))

print("first matrix",arr1)

print("second matrix",arr1)

mul = arr1 @ arr2

print("mul of matrix arr1 and aarr2",mul)

first matrix [[2 7 8]
 [2 3 6]
 [5 4 4]]
second matrix [[2 7 8]
 [2 3 6]
 [5 4 4]]
mul of matrix arr1 and aarr2 [[102  54 123]
 [ 64  32  77]
 [ 62  33  69]]


In [17]:
#83. Create a matrix `E` and find its transpose


arr1 = np.random.randint(1,10,(3,3))
print(arr1)
arr1.T

[[9 2 2]
 [7 5 6]
 [3 7 9]]


array([[9, 7, 3],
       [2, 5, 7],
       [2, 6, 9]])

In [18]:
#84.Generate a square matrix `F` and compute its determinant.
import numpy as np


F = np.random.randint(1, 10, size=(3, 3))


determinant = np.linalg.det(F)

print("Square matrix F:")
print(F)
print("Determinant of F:", determinant)


Square matrix F:
[[5 9 9]
 [9 3 7]
 [3 8 8]]
Determinant of F: -51.999999999999986


In [19]:
#85.5. Create a square matrix `G` and find its inverse.
import numpy as np

# Step 1: Generate a square matrix G of shape (3, 3) with random integers
G = np.random.randint(1, 10, size=(3, 3))

# Step 2: Compute the inverse of G
try:
    G_inverse = np.linalg.inv(G)
except np.linalg.LinAlgError:
    G_inverse = None

print("Square matrix G:")
print(G)
if G_inverse is not None:
    print("Inverse of G:")
    print(G_inverse)
else:
    print("Matrix G is singular and does not have an inverse.")


Square matrix G:
[[2 4 6]
 [7 6 7]
 [3 3 8]]
Inverse of G:
[[-0.39705882  0.20588235  0.11764706]
 [ 0.51470588  0.02941176 -0.41176471]
 [-0.04411765 -0.08823529  0.23529412]]
